/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalhormiserver;

import java.util.ArrayList;

/**
 *
 * @author asuspc
 */
public class InscricaoTopicos extends javax.swing.JDialog {

    private Usuario usuarioAtual;
    private Boolean inscrever;
    private TopicoTableModel tmTopico;
    
    public InscricaoTopicos(java.awt.Frame parent, boolean modal, Usuario usuarioAtual, Boolean inscrever) {
        super(parent, modal);
        initComponents();
        Util.centralizaTela(this);
        this.usuarioAtual = usuarioAtual;        
        tbTopicos.setModel(new TopicoTableModel());
        tmTopico = (TopicoTableModel) tbTopicos.getModel();
        tbTopicos.setRowHeight(25);
        tbTopicos.getColumnModel().getColumn(0).setMaxWidth(30);        
        this.inscrever = inscrever;
        try{
            if (this.inscrever){
                btInscrever.setText("Inscrever"); 
                setTitle("Inscrição em tópicos");
            } else {
                btInscrever.setText("Desinscrever");
                setTitle("Desinscrição em tópicos");
            }
            AtualizaTopicos();
        } catch (Exception e){
            Util.MensagemErro(this, "Erro ao consultar tópicos: " + e.getMessage());
        }
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbTopicos = new javax.swing.JTable();
        btInscrever = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tbTopicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbTopicos);

        btInscrever.setText("jButton1");
        btInscrever.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInscreverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(btInscrever)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btInscrever)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btInscreverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInscreverActionPerformed
        try{           
            for (Topico t : tmTopico.getTopicosSelecionados()){
                if (inscrever){
                    Cliente.getInstance()._service.inscreverUsuario(usuarioAtual.login, t.codigo);
                } else {
                    Cliente.getInstance()._service.desinscreverUsuario(usuarioAtual.login, t.codigo);
                }
            }
            AtualizaTopicos();
            
        } catch (Exception e){
            Util.MensagemErro(this, "Erro ao inscrever/desincrever: " + e.getMessage());
        }
    }//GEN-LAST:event_btInscreverActionPerformed

    private void AtualizaTopicos(){
        tmTopico.limpar();
        try{
            if (inscrever){             
                tmTopico.addAll(Cliente.getInstance()._service.getTopicosNaoInscritos(this.usuarioAtual.login));
            } else {                
                tmTopico.addAll(Cliente.getInstance()._service.getTopicosInscritos(this.usuarioAtual.login));
            }            
        } catch(Exception e){
            Util.MensagemErro(this, "Erro ao atualizar tópicos: " + e.getMessage());
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btInscrever;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbTopicos;
    // End of variables declaration//GEN-END:variables
}
